version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: mockserver
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - .:.
    command: node server.js